-- Invite + notification + outbox migrations (idempotent).
-- Execute after table_initialization.sql and priority_migrations.sql.

CREATE TABLE IF NOT EXISTS group_invites (
  invite_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id INTEGER NOT NULL REFERENCES groups (id) ON DELETE CASCADE,
  created_by_user_id INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  target_email TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  expires_at TIMESTAMPTZ NOT NULL,
  accepted_by_user_id INTEGER REFERENCES users (id) ON DELETE SET NULL,
  accepted_at TIMESTAMPTZ,
  revoked_by_user_id INTEGER REFERENCES users (id) ON DELETE SET NULL,
  revoked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (status IN ('PENDING', 'ACCEPTED', 'REVOKED', 'EXPIRED')),
  CHECK (
    (status = 'ACCEPTED' AND accepted_at IS NOT NULL)
    OR (status <> 'ACCEPTED')
  )
);

CREATE INDEX IF NOT EXISTS idx_group_invites_group_status
  ON group_invites (group_id, status);

CREATE INDEX IF NOT EXISTS idx_group_invites_expires_at
  ON group_invites (expires_at);

CREATE INDEX IF NOT EXISTS idx_group_invites_target_email
  ON group_invites (target_email);

CREATE TABLE IF NOT EXISTS notifications (
  notification_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient_user_id INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  type VARCHAR(50) NOT NULL,
  event_key TEXT,
  payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  read_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (is_read = FALSE OR read_at IS NOT NULL)
);

ALTER TABLE notifications
  ADD COLUMN IF NOT EXISTS event_key TEXT;

CREATE INDEX IF NOT EXISTS idx_notifications_recipient_unread_created
  ON notifications (recipient_user_id, is_read, created_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS uniq_notifications_recipient_event_key
  ON notifications (recipient_user_id, event_key)
  WHERE event_key IS NOT NULL;

CREATE TABLE IF NOT EXISTS notification_outbox (
  outbox_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notification_id INTEGER NOT NULL REFERENCES notifications (notification_id) ON DELETE CASCADE,
  channel VARCHAR(20) NOT NULL DEFAULT 'EMAIL',
  dedupe_key TEXT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  attempt_count INTEGER NOT NULL DEFAULT 0,
  next_attempt_at TIMESTAMPTZ,
  last_error TEXT,
  sent_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (status IN ('PENDING', 'PROCESSING', 'SENT', 'FAILED', 'DEAD')),
  CHECK (attempt_count >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS uniq_notification_outbox_dedupe
  ON notification_outbox (dedupe_key);

CREATE INDEX IF NOT EXISTS idx_notification_outbox_status_next_attempt
  ON notification_outbox (status, next_attempt_at, outbox_id);
