-- Priority + persistence migrations (idempotent).
-- This file is intended to be executed AFTER table_initialization.sql.

-- 1) Sync metadata (1:1 with calendar)
CREATE TABLE IF NOT EXISTS calendar_sync_state (
  calendar_id INTEGER PRIMARY KEY REFERENCES calendar (calendar_id) ON DELETE CASCADE,
  sync_token TEXT,
  last_synced_at TIMESTAMPTZ,
  last_full_synced_at TIMESTAMPTZ,
  last_error TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_calendar_sync_state_last_synced
  ON calendar_sync_state (last_synced_at);

-- 2) Manual user-created busy blocks
CREATE TABLE IF NOT EXISTS user_busy_block (
  busy_block_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  title VARCHAR(255),
  start_time TIMESTAMPTZ NOT NULL,
  end_time TIMESTAMPTZ NOT NULL,
  blocking_level VARCHAR(2) NOT NULL DEFAULT 'B3',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (end_time > start_time),
  CHECK (blocking_level IN ('B1', 'B2', 'B3'))
);

CREATE INDEX IF NOT EXISTS idx_busy_block_user_start
  ON user_busy_block (user_id, start_time);

CREATE INDEX IF NOT EXISTS idx_busy_block_user_time_range
  ON user_busy_block (user_id, start_time, end_time);

-- 3) Petitions: enforce time ordering
ALTER TABLE petitions DROP CONSTRAINT IF EXISTS petitions_time_order_chk;
ALTER TABLE petitions
  ADD CONSTRAINT petitions_time_order_chk
  CHECK (end_time > start_time);

-- 4) Google event persistence upgrades (cal_event)
ALTER TABLE cal_event DROP COLUMN IF EXISTS priority;

ALTER TABLE cal_event ADD COLUMN IF NOT EXISTS provider_event_id TEXT;
ALTER TABLE cal_event ADD COLUMN IF NOT EXISTS ical_uid TEXT;
ALTER TABLE cal_event ADD COLUMN IF NOT EXISTS recurring_event_id TEXT;
ALTER TABLE cal_event ADD COLUMN IF NOT EXISTS original_start_time TIMESTAMPTZ;
ALTER TABLE cal_event ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE cal_event ADD COLUMN IF NOT EXISTS provider_updated_at TIMESTAMPTZ;
ALTER TABLE cal_event ADD COLUMN IF NOT EXISTS etag TEXT;
ALTER TABLE cal_event ADD COLUMN IF NOT EXISTS blocking_level VARCHAR(2);
ALTER TABLE cal_event ADD COLUMN IF NOT EXISTS last_synced_at TIMESTAMPTZ;

UPDATE cal_event SET status = 'confirmed' WHERE status IS NULL;
UPDATE cal_event SET blocking_level = 'B3' WHERE blocking_level IS NULL;
UPDATE cal_event SET last_synced_at = NOW() WHERE last_synced_at IS NULL;

ALTER TABLE cal_event ALTER COLUMN status SET DEFAULT 'confirmed';
ALTER TABLE cal_event ALTER COLUMN blocking_level SET DEFAULT 'B3';
ALTER TABLE cal_event ALTER COLUMN last_synced_at SET DEFAULT NOW();

ALTER TABLE cal_event ALTER COLUMN status SET NOT NULL;
ALTER TABLE cal_event ALTER COLUMN blocking_level SET NOT NULL;
ALTER TABLE cal_event ALTER COLUMN last_synced_at SET NOT NULL;

ALTER TABLE cal_event DROP CONSTRAINT IF EXISTS cal_event_status_chk;
ALTER TABLE cal_event
  ADD CONSTRAINT cal_event_status_chk
  CHECK (status IN ('confirmed', 'tentative', 'cancelled'));

ALTER TABLE cal_event DROP CONSTRAINT IF EXISTS cal_event_blocking_level_chk;
ALTER TABLE cal_event
  ADD CONSTRAINT cal_event_blocking_level_chk
  CHECK (blocking_level IN ('B1', 'B2', 'B3'));

DROP INDEX IF EXISTS uniq_cal_event_gcal;
CREATE UNIQUE INDEX IF NOT EXISTS uniq_cal_event_provider
  ON cal_event (calendar_id, provider_event_id);

