-- Sync reliability hardening migrations (idempotent).
-- Execute after table_initialization.sql and priority_migrations.sql.

ALTER TABLE calendar_sync_state
  ADD COLUMN IF NOT EXISTS last_success_sync_token TEXT,
  ADD COLUMN IF NOT EXISTS last_attempted_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_succeeded_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_error_code TEXT,
  ADD COLUMN IF NOT EXISTS last_error_details JSONB,
  ADD COLUMN IF NOT EXISTS consecutive_failures INTEGER,
  ADD COLUMN IF NOT EXISTS needs_reauth BOOLEAN,
  ADD COLUMN IF NOT EXISTS in_progress BOOLEAN,
  ADD COLUMN IF NOT EXISTS in_progress_started_at TIMESTAMPTZ;

UPDATE calendar_sync_state
SET last_success_sync_token = COALESCE(last_success_sync_token, sync_token)
WHERE last_success_sync_token IS NULL;

UPDATE calendar_sync_state
SET consecutive_failures = 0
WHERE consecutive_failures IS NULL;

UPDATE calendar_sync_state
SET needs_reauth = FALSE
WHERE needs_reauth IS NULL;

UPDATE calendar_sync_state
SET in_progress = FALSE
WHERE in_progress IS NULL;

ALTER TABLE calendar_sync_state
  ALTER COLUMN consecutive_failures SET DEFAULT 0,
  ALTER COLUMN consecutive_failures SET NOT NULL,
  ALTER COLUMN needs_reauth SET DEFAULT FALSE,
  ALTER COLUMN needs_reauth SET NOT NULL,
  ALTER COLUMN in_progress SET DEFAULT FALSE,
  ALTER COLUMN in_progress SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_calendar_sync_state_needs_reauth
  ON calendar_sync_state (needs_reauth);

CREATE INDEX IF NOT EXISTS idx_calendar_sync_state_in_progress
  ON calendar_sync_state (in_progress)
  WHERE in_progress = TRUE;

CREATE TABLE IF NOT EXISTS calendar_sync_run (
  run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  calendar_id INTEGER NOT NULL REFERENCES calendar (calendar_id) ON DELETE CASCADE,
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  finished_at TIMESTAMPTZ,
  status VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS',
  attempt INTEGER NOT NULL DEFAULT 1,
  sync_token_in TEXT,
  sync_token_out TEXT,
  items_seen INTEGER NOT NULL DEFAULT 0,
  items_upserted INTEGER NOT NULL DEFAULT 0,
  items_cancelled INTEGER NOT NULL DEFAULT 0,
  error_code TEXT,
  error_payload JSONB,
  CHECK (status IN ('IN_PROGRESS', 'SUCCESS', 'FAILED')),
  CHECK (attempt >= 1),
  CHECK (items_seen >= 0),
  CHECK (items_upserted >= 0),
  CHECK (items_cancelled >= 0)
);

CREATE INDEX IF NOT EXISTS idx_calendar_sync_run_calendar_started
  ON calendar_sync_run (calendar_id, started_at DESC);

CREATE INDEX IF NOT EXISTS idx_calendar_sync_run_status
  ON calendar_sync_run (status, started_at DESC);

ALTER TABLE cal_event
  ADD COLUMN IF NOT EXISTS is_all_day BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS event_timezone TEXT;

CREATE INDEX IF NOT EXISTS idx_cal_event_calendar_status_window
  ON cal_event (calendar_id, status, event_start, event_end);

CREATE INDEX IF NOT EXISTS idx_cal_event_calendar_active_window
  ON cal_event (calendar_id, event_start, event_end)
  WHERE status <> 'cancelled';

CREATE INDEX IF NOT EXISTS idx_petition_responses_petition_response_user
  ON petition_responses (petition_id, response, user_id);
