-- MVP schema: ONLY users, groups, group_memberships (plus session table managed by connect-pg-simple).

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  google_sub VARCHAR(255) UNIQUE,
  email VARCHAR(255) UNIQUE NOT NULL,
  name VARCHAR(255),
  google_refresh_token TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS groups (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  created_by_user_id INTEGER NOT NULL REFERENCES users (id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS group_memberships (
  group_id INTEGER NOT NULL REFERENCES groups (id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  role VARCHAR(50),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (group_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_group_memberships_user_id ON group_memberships (user_id);

CREATE TABLE IF NOT EXISTS petitions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id INTEGER NOT NULL REFERENCES groups (id) ON DELETE CASCADE,
  created_by_user_id INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  start_time TIMESTAMPTZ NOT NULL,
  end_time TIMESTAMPTZ NOT NULL,
  priority VARCHAR(20) NOT NULL DEFAULT 'HIGHEST',
  status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (status IN ('OPEN', 'FAILED', 'ACCEPTED_ALL')),
  CHECK (priority IN ('HIGHEST', 'HIGH', 'MEDIUM', 'LOW'))
);

CREATE TABLE IF NOT EXISTS petition_responses (
  petition_id INTEGER NOT NULL REFERENCES petitions (id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  response VARCHAR(20) NOT NULL,
  responded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (petition_id, user_id),
  CHECK (response IN ('ACCEPTED', 'DECLINED'))
);

CREATE INDEX IF NOT EXISTS idx_petitions_group_id ON petitions (group_id);
CREATE INDEX IF NOT EXISTS idx_petitions_time_range ON petitions (start_time, end_time);
CREATE INDEX IF NOT EXISTS idx_petition_responses_user ON petition_responses (user_id);

CREATE TABLE IF NOT EXISTS calendar (
  calendar_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  gcal_id VARCHAR(255) NOT NULL,
  calendar_name VARCHAR(255)
);

CREATE UNIQUE INDEX IF NOT EXISTS uniq_calendar_user_gcal
  ON calendar (user_id, gcal_id);

CREATE TABLE IF NOT EXISTS cal_event (
  event_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  calendar_id INTEGER NOT NULL REFERENCES calendar (calendar_id) ON DELETE CASCADE,
  gcal_event_id VARCHAR(255) NOT NULL,
  event_name VARCHAR(255),
  event_start TIMESTAMPTZ NOT NULL,
  event_end TIMESTAMPTZ NOT NULL,
  priority INTEGER DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_calendar_user
  ON calendar (user_id);

CREATE INDEX IF NOT EXISTS idx_cal_event_calendar_start
  ON cal_event (calendar_id, event_start);

ALTER TABLE cal_event DROP CONSTRAINT IF EXISTS cal_event_time_order_chk;
ALTER TABLE cal_event
  ADD CONSTRAINT cal_event_time_order_chk
  CHECK (event_end > event_start);
